console.log("GOOGLE_SHEETS_SPREADSHEET_ID:", !!process.env.GOOGLE_SHEETS_SPREADSHEET_ID);
console.log("GOOGLE_SHEETS_CLIENT_EMAIL:", !!process.env.GOOGLE_SHEETS_CLIENT_EMAIL);
console.log("GOOGLE_SHEETS_PRIVATE_KEY:", !!process.env.GOOGLE_SHEETS_PRIVATE_KEY);
